activities = [{"name": "actionable_type", "type": "varchar(256)"},
              {"name": "actionable_id", "type": "int"},
              {"name": "targetable_name", "type": "varchar(256)"},
              {"name": "targetable_type", "type": "varchar(256)"},
              {"name": "targetable_id", "type": "int"},
              {"name": "user_activity", "type": "boolean"},
              {"name": "composite_id", "type": "varchar(256)"},
              {"name": "action_type", "type": "varchar(256)"},
              {"name": "automation", "type": "varchar(256)"},
              {"name": "created_at", "type": "timestamptz"},
              {"name": "action_data_property_key", "type": "varchar(256)"},
              {"name": "action_data_property_value", "type": "varchar(256)"},
              {"name": "action_data_count", "type": "int"},
              {"name": "action_data_first_occurrence", "type": "timestamptz"},
              {"name": "action_data_name", "type": "varchar(256)"},
              {"name": "action_data_last_occurrence", "type": "timestamptz"}]
