contacts = [
    {'name': 'id', 'type': 'BIGINT'},
    {'name': 'custom_field_cf_nickname', 'type': 'VARCHAR'},
    {'name': 'email_status', 'type': 'VARCHAR'},
    {'name': 'email', 'type': 'VARCHAR'},
    {'name': 'mobile_number', 'type': 'VARCHAR'},
    {'name': 'state', 'type': 'VARCHAR'},
    {'name': 'won_deals_amount', 'type': 'FLOAT'},
    {'name': 'avatar', 'type': 'VARCHAR'},
    {'name': 'open_deals_amount', 'type': 'FLOAT'},
    {'name': 'links_notes', 'type': 'VARCHAR'},
    {'name': 'links_timeline_feeds', 'type': 'VARCHAR'},
    {'name': 'links_conversations', 'type': 'VARCHAR'},
    {'name': 'links_appointments', 'type': 'VARCHAR'},
    {'name': 'links_tasks', 'type': 'VARCHAR'},
    {'name': 'custom_field_cf_email_work', 'type': 'VARCHAR'},
    {'name': 'custom_field_cf_applicant_id_ezlynx', 'type': 'VARCHAR'},
    {'name': 'custom_field_cf_relation', 'type': 'VARCHAR'},
    {'name': 'custom_field_cf_unit_', 'type': 'VARCHAR'},
    {'name': 'twitter', 'type': 'VARCHAR'},
    {'name': 'do_not_disturb', 'type': 'VARCHAR'},
    {'name': 'last_contacted_via_chat',
     'type': 'TIMESTAMP WITH TIME ZONE'},
    {'name': 'custom_field_cf_vip', 'type': 'VARCHAR'},
    {'name': 'facebook', 'type': 'VARCHAR'},
    {'name': 'custom_field_cf_coapplicantid', 'type': 'VARCHAR'},
    {'name': 'updated_at', 'type': 'TIMESTAMP WITH TIME ZONE'},
    {'name': 'last_contacted', 'type': 'VARCHAR'},
    {'name': 'keyword', 'type': 'VARCHAR'},
    {'name': 'work_number', 'type': 'VARCHAR'},
    {'name': 'recent_note', 'type': 'VARCHAR'},
    {'name': 'time_zone', 'type': 'VARCHAR'},
    {'name': 'completed_sales_sequences', 'type': 'VARCHAR'},
    {'name': 'display_name', 'type': 'VARCHAR'},
    {'name': 'zipcode', 'type': 'VARCHAR'},
    {'name': 'last_name', 'type': 'VARCHAR'},
    {'name': 'country', 'type': 'VARCHAR'},
    {'name': 'last_contacted_sales_activity_mode', 'type': 'VARCHAR'},
    {'name': 'web_form_ids', 'type': 'VARCHAR'},
    {'name': 'address', 'type': 'VARCHAR'},
    {'name': 'custom_field_cf_home_phone_', 'type': 'VARCHAR'},
    {'name': 'job_title', 'type': 'VARCHAR'},
    {'name': 'last_contacted_mode', 'type': 'VARCHAR'},
    {'name': 'lead_quality', 'type': 'VARCHAR'},
    {'name': 'first_name', 'type': 'VARCHAR'},
    {'name': 'active_sales_sequences', 'type': 'VARCHAR'},
    {'name': 'lead_score', 'type': 'FLOAT'},
    {'name': 'last_contacted_via_sales_activity',
        'type': 'TIMESTAMP WITH TIME ZONE'},
    {'name': 'city', 'type': 'VARCHAR'},
    {'name': 'medium', 'type': 'VARCHAR'},
    {'name': 'created_at', 'type': 'TIMESTAMP WITH TIME ZONE'},
    {'name': 'last_seen', 'type': 'TIMESTAMP WITH TIME ZONE'}
]
