leads = [{"name": "custom_field_cf_home", "type": "VARCHAR"},
           {"name": "address", "type": "VARCHAR"},
           {"name": "department", "type": "VARCHAR"},
           {"name": "email_status", "type": "VARCHAR"},
           {"name": "company_annual_revenue", "type": "FLOAT"},
           {"name": "web_form_ids",  "type": "VARCHAR"},
           {"name": "mobile_number", "type": "VARCHAR"},
           {"name": "links_conversations", "type": "VARCHAR"},
           {"name": "deal", "type": "VARCHAR"},
           {"name": "active_sales_sequences", "type": "VARCHAR"},
           {"name": "keyword", "type": "VARCHAR"},
           {"name": "custom_field_cf_phone", "type": "VARCHAR"},
           {"name": "links_tasks", "type": "VARCHAR"},
           {"name": "twitter", "type": "VARCHAR"},
           {"name": "custom_field_cf_name", "type": "VARCHAR"},
           {"name": "company_name", "type": "VARCHAR"},
           {"name": "links_notes", "type": "VARCHAR"},
           {"name": "recent_note", "type": "VARCHAR"},
           {"name": "company_business_type_id", "type": "VARCHAR"},
           {"name": "company_business_type", "type": "VARCHAR"},
           {"name": "linkedin", "type": "VARCHAR"},
           {"name": "id", "type": "VARCHAR"},
           {"name": "display_name", "type": "VARCHAR"},
           {"name": "company_country", "type": "VARCHAR"},
           {"name": "country", "type": "VARCHAR"},
           {"name": "has_authority", "type": "VARCHAR"},
           {"name": "avatar", "type": "VARCHAR"},
           {"name": "links_appointments", "type": "VARCHAR"},
           {"name": "last_contacted_via_chat",
               "type": "TIMESTAMP WITH TIME ZONE"},
           {"name": "last_name", "type": "VARCHAR"},
           {"name": "last_seen", "type": "TIMESTAMP WITH TIME ZONE"},
           {"name": "custom_field_cf_home_phone", "type": "VARCHAR"},
           {"name": "custom_field_cf_amount", "type": "VARCHAR"},
           {"name": "company_address", "type": "VARCHAR"},
           {"name": "do_not_disturb", "type": "VARCHAR"},
           {"name": "created_at", "type": "TIMESTAMP WITH TIME ZONE"},
           {"name": "work_number", "type": "VARCHAR"},
           {"name": "lead_score", "type": "FLOAT"},
           {"name": "custom_field_cf_alternate_contact_number",
               "type": "VARCHAR"},
           {"name": "last_contacted", "type": "TIMESTAMP WITH TIME ZONE"},
           {"name": "facebook", "type": "VARCHAR"},
           {"name": "links_document_associations", "type": "VARCHAR"},
           {"name": "state", "type": "VARCHAR"},
           {"name": "company_zipcode", "type": "VARCHAR"},
           {"name": "email", "type": "VARCHAR"},
           {"name": "company_state", "type": "VARCHAR"},
           {"name": "zipcode", "type": "VARCHAR"},
           {"name": "company_id", "type": "BIGINT"},
           {"name": "company_number_of_employees", "type": "INT"},
           {"name": "links_timeline_feeds", "type": "VARCHAR"},
           {"name": "company_phone", "type": "VARCHAR"},
           {"name": "company_industry_type_id", "type": "VARCHAR"},
           {"name": "company_city", "type": "VARCHAR"},
           {"name": "company_website", "type": "VARCHAR"},
           {"name": "job_title", "type": "VARCHAR"},
           {"name": "lead_quality", "type": "VARCHAR"},
           {"name": "custom_field_cf_unit", "type": "VARCHAR"},
           {"name": "last_contacted_mode", "type": "VARCHAR"},
           {"name": "last_contacted_via_sales_activity",
            "type": "TIMESTAMP WITH TIME ZONE"},
           {"name": "updated_at", "type": "TIMESTAMP WITH TIME ZONE"},
           {"name": "city", "type": "VARCHAR"},
           {"name": "stage_updated_time",
               "type": "TIMESTAMP WITH TIME ZONE"},
           {"name": "completed_sales_sequences", "type": "VARCHAR"},
           {"name": "company_industry_type", "type": "VARCHAR"},
           {"name": "medium", "type": "VARCHAR"},
           {"name": "last_contacted_sales_activity_mode",
            "type": "TIMESTAMP WITH TIME ZONE"},
           {"name": "first_name", "type": "VARCHAR"},
           {"name": "custom_field_cf_email_2", "type": "VARCHAR"},
           {"name": "time_zone", "type": "VARCHAR"}]
