sales_accounts = [
    {'name': 'id', 'type': 'BIGINT'},
    {'name': 'won_deals_amount', 'type': 'FLOAT'},
    {'name': 'active_sales_sequences', 'type': 'VARCHAR'},
    {'name': 'custom_field_cf_home', 'type': 'VARCHAR'},
    {'name': 'last_contacted_mode', 'type': 'VARCHAR'},
    {'name': 'last_contacted_via_sales_activity', 'type': 'VARCHAR'},
    {'name': 'state', 'type': 'VARCHAR'},
    {'name': 'owner_id', 'type': 'VARCHAR'},
    {'name': 'twitter', 'type': 'VARCHAR'},
    {'name': 'last_contacted', 'type': 'TIMESTAMP WITH TIME ZONE'},
    {'name': 'parent_sales_account_id', 'type': 'VARCHAR'},
    {'name': 'number_of_employees', 'type': 'INT'},
    {'name': 'avatar', 'type': 'VARCHAR'},
    {'name': 'annual_revenue', 'type': 'FLOAT'},
    {'name': 'country', 'type': 'VARCHAR'},
    {'name': 'name', 'type': 'VARCHAR'},
    {'name': 'last_contacted_via_chat',
     'type': 'TIMESTAMP WITH TIME ZONE'},
    {'name': 'links_conversations', 'type': 'VARCHAR'},
    {'name': 'links_document_associations', 'type': 'VARCHAR'},
    {'name': 'links_notes', 'type': 'VARCHAR'},
    {'name': 'links_tasks', 'type': 'VARCHAR'},
    {'name': 'links_appointments', 'type': 'VARCHAR'},
    {'name': 'recent_note', 'type': 'VARCHAR'},
    {'name': 'zipcode', 'type': 'VARCHAR'},
    {'name': 'open_deals_amount', 'type': 'FLOAT'},
    {'name': 'last_contacted_sales_activity_mode',
        'type': 'TIMESTAMP WITH TIME ZONE'},
    {'name': 'updated_at', 'type': 'TIMESTAMP WITH TIME ZONE'},
    {'name': 'phone', 'type': 'VARCHAR'},
    {'name': 'address', 'type': 'VARCHAR'},
    {'name': 'website', 'type': 'VARCHAR'},
    {'name': 'facebook', 'type': 'VARCHAR'},
    {'name': 'completed_sales_sequences', 'type': 'VARCHAR'},
    {'name': 'city', 'type': 'VARCHAR'},
    {'name': 'linkedin', 'type': 'VARCHAR'}
]
